# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

price_arithmetic_asian_diffusion_mc_cpp <- function(S0, K, r, sigma, T_mat, lambda_T, I0, kappa, eta_values, rho, n_steps, n_sims, option_type, use_control_variate, seed) {
    .Call(`_AsianOption_price_arithmetic_asian_diffusion_mc_cpp`, S0, K, r, sigma, T_mat, lambda_T, I0, kappa, eta_values, rho, n_steps, n_sims, option_type, use_control_variate, seed)
}

hjb_arithmetic_value_cpp <- function(S0, K, T, N, sigma, r_cont, kappa, lambda_bar_T, lambda_bar_P, k_A, k_B, psi_cost, eta_vec, p, I0, control_set, n_logS, n_I, n_Y, payoff_sign, store_policy = FALSE) {
    .Call(`_AsianOption_hjb_arithmetic_value_cpp`, S0, K, T, N, sigma, r_cont, kappa, lambda_bar_T, lambda_bar_P, k_A, k_B, psi_cost, eta_vec, p, I0, control_set, n_logS, n_I, n_Y, payoff_sign, store_policy)
}

hjb_geometric_value_cpp <- function(S0, K, T, N, sigma, r_cont, kappa, lambda_bar_T, lambda_bar_P, k_A, k_B, psi_cost, eta_vec, p, I0, control_set, n_logS, n_I, n_Y, payoff_sign, store_policy = FALSE) {
    .Call(`_AsianOption_hjb_geometric_value_cpp`, S0, K, T, N, sigma, r_cont, kappa, lambda_bar_T, lambda_bar_P, k_A, k_B, psi_cost, eta_vec, p, I0, control_set, n_logS, n_I, n_Y, payoff_sign, store_policy)
}

hjb_arithmetic_quotes_cpp <- function(S0, K, T, N, sigma, r_cont, kappa, lambda_bar_T, lambda_bar_P, k_A, k_B, psi_cost, eta_vec, p, I0, control_set, n_logS, n_I, n_Y) {
    .Call(`_AsianOption_hjb_arithmetic_quotes_cpp`, S0, K, T, N, sigma, r_cont, kappa, lambda_bar_T, lambda_bar_P, k_A, k_B, psi_cost, eta_vec, p, I0, control_set, n_logS, n_I, n_Y)
}

hjb_arithmetic_quotes_with_policy_cpp <- function(S0, K, T, N, sigma, r_cont, kappa, lambda_bar_T, lambda_bar_P, k_A, k_B, psi_cost, eta_vec, p, I0, control_set, n_logS, n_I, n_Y) {
    .Call(`_AsianOption_hjb_arithmetic_quotes_with_policy_cpp`, S0, K, T, N, sigma, r_cont, kappa, lambda_bar_T, lambda_bar_P, k_A, k_B, psi_cost, eta_vec, p, I0, control_set, n_logS, n_I, n_Y)
}

hjb_geometric_quotes_with_policy_cpp <- function(S0, K, T, N, sigma, r_cont, kappa, lambda_bar_T, lambda_bar_P, k_A, k_B, psi_cost, eta_vec, p, I0, control_set, n_logS, n_I, n_Y) {
    .Call(`_AsianOption_hjb_geometric_quotes_with_policy_cpp`, S0, K, T, N, sigma, r_cont, kappa, lambda_bar_T, lambda_bar_P, k_A, k_B, psi_cost, eta_vec, p, I0, control_set, n_logS, n_I, n_Y)
}

hjb_geometric_quotes_cpp <- function(S0, K, T, N, sigma, r_cont, kappa, lambda_bar_T, lambda_bar_P, k_A, k_B, psi_cost, eta_vec, p, I0, control_set, n_logS, n_I, n_Y) {
    .Call(`_AsianOption_hjb_geometric_quotes_cpp`, S0, K, T, N, sigma, r_cont, kappa, lambda_bar_T, lambda_bar_P, k_A, k_B, psi_cost, eta_vec, p, I0, control_set, n_logS, n_I, n_Y)
}

price_kemna_vorst_arithmetic_cpp <- function(S0, K, r, sigma, T0, T_mat, n, M, option_type = "call", use_control_variate = TRUE, seed = 0L) {
    .Call(`_AsianOption_price_kemna_vorst_arithmetic_cpp`, S0, K, r, sigma, T0, T_mat, n, M, option_type, use_control_variate, seed)
}

price_kemna_vorst_arithmetic_binomial_cpp <- function(S0, K, r, u, d, n, M, option_type = "call", use_control_variate = TRUE, seed = 0L) {
    .Call(`_AsianOption_price_kemna_vorst_arithmetic_binomial_cpp`, S0, K, r, u, d, n, M, option_type, use_control_variate, seed)
}

