// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// price_arithmetic_asian_diffusion_mc_cpp
List price_arithmetic_asian_diffusion_mc_cpp(double S0, double K, double r, double sigma, double T_mat, double lambda_T, double I0, double kappa, NumericVector eta_values, double rho, int n_steps, int n_sims, std::string option_type, bool use_control_variate, int seed);
RcppExport SEXP _AsianOption_price_arithmetic_asian_diffusion_mc_cpp(SEXP S0SEXP, SEXP KSEXP, SEXP rSEXP, SEXP sigmaSEXP, SEXP T_matSEXP, SEXP lambda_TSEXP, SEXP I0SEXP, SEXP kappaSEXP, SEXP eta_valuesSEXP, SEXP rhoSEXP, SEXP n_stepsSEXP, SEXP n_simsSEXP, SEXP option_typeSEXP, SEXP use_control_variateSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type S0(S0SEXP);
    Rcpp::traits::input_parameter< double >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type T_mat(T_matSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_T(lambda_TSEXP);
    Rcpp::traits::input_parameter< double >::type I0(I0SEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type eta_values(eta_valuesSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< int >::type n_steps(n_stepsSEXP);
    Rcpp::traits::input_parameter< int >::type n_sims(n_simsSEXP);
    Rcpp::traits::input_parameter< std::string >::type option_type(option_typeSEXP);
    Rcpp::traits::input_parameter< bool >::type use_control_variate(use_control_variateSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(price_arithmetic_asian_diffusion_mc_cpp(S0, K, r, sigma, T_mat, lambda_T, I0, kappa, eta_values, rho, n_steps, n_sims, option_type, use_control_variate, seed));
    return rcpp_result_gen;
END_RCPP
}
// arithmetic_asian_bounds_cpp
Rcpp::List arithmetic_asian_bounds_cpp(double S0, double K, double r, double u, double d, double lambda, double v_u, double v_d, int n, std::string option_type);
RcppExport SEXP _AsianOption_arithmetic_asian_bounds_cpp(SEXP S0SEXP, SEXP KSEXP, SEXP rSEXP, SEXP uSEXP, SEXP dSEXP, SEXP lambdaSEXP, SEXP v_uSEXP, SEXP v_dSEXP, SEXP nSEXP, SEXP option_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type S0(S0SEXP);
    Rcpp::traits::input_parameter< double >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type u(uSEXP);
    Rcpp::traits::input_parameter< double >::type d(dSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type v_u(v_uSEXP);
    Rcpp::traits::input_parameter< double >::type v_d(v_dSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< std::string >::type option_type(option_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(arithmetic_asian_bounds_cpp(S0, K, r, u, d, lambda, v_u, v_d, n, option_type));
    return rcpp_result_gen;
END_RCPP
}
// arithmetic_asian_bounds_extended_cpp
Rcpp::List arithmetic_asian_bounds_extended_cpp(double S0, double K, double r, double u, double d, double lambda, double v_u, double v_d, int n, bool compute_path_specific, std::string option_type);
RcppExport SEXP _AsianOption_arithmetic_asian_bounds_extended_cpp(SEXP S0SEXP, SEXP KSEXP, SEXP rSEXP, SEXP uSEXP, SEXP dSEXP, SEXP lambdaSEXP, SEXP v_uSEXP, SEXP v_dSEXP, SEXP nSEXP, SEXP compute_path_specificSEXP, SEXP option_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type S0(S0SEXP);
    Rcpp::traits::input_parameter< double >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type u(uSEXP);
    Rcpp::traits::input_parameter< double >::type d(dSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type v_u(v_uSEXP);
    Rcpp::traits::input_parameter< double >::type v_d(v_dSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< bool >::type compute_path_specific(compute_path_specificSEXP);
    Rcpp::traits::input_parameter< std::string >::type option_type(option_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(arithmetic_asian_bounds_extended_cpp(S0, K, r, u, d, lambda, v_u, v_d, n, compute_path_specific, option_type));
    return rcpp_result_gen;
END_RCPP
}
// arithmetic_asian_bounds_transient_cpp
Rcpp::List arithmetic_asian_bounds_transient_cpp(double S0, double K, double r, double u, double d, double lambda_P, double lambda_T, double alpha, double psi, Rcpp::NumericVector volumes, bool compute_path_specific, std::string option_type);
RcppExport SEXP _AsianOption_arithmetic_asian_bounds_transient_cpp(SEXP S0SEXP, SEXP KSEXP, SEXP rSEXP, SEXP uSEXP, SEXP dSEXP, SEXP lambda_PSEXP, SEXP lambda_TSEXP, SEXP alphaSEXP, SEXP psiSEXP, SEXP volumesSEXP, SEXP compute_path_specificSEXP, SEXP option_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type S0(S0SEXP);
    Rcpp::traits::input_parameter< double >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type u(uSEXP);
    Rcpp::traits::input_parameter< double >::type d(dSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_P(lambda_PSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_T(lambda_TSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type psi(psiSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type volumes(volumesSEXP);
    Rcpp::traits::input_parameter< bool >::type compute_path_specific(compute_path_specificSEXP);
    Rcpp::traits::input_parameter< std::string >::type option_type(option_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(arithmetic_asian_bounds_transient_cpp(S0, K, r, u, d, lambda_P, lambda_T, alpha, psi, volumes, compute_path_specific, option_type));
    return rcpp_result_gen;
END_RCPP
}
// price_european_call_cpp
double price_european_call_cpp(double S0, double K, double r, double u, double d, double lambda, double v_u, double v_d, int n);
RcppExport SEXP _AsianOption_price_european_call_cpp(SEXP S0SEXP, SEXP KSEXP, SEXP rSEXP, SEXP uSEXP, SEXP dSEXP, SEXP lambdaSEXP, SEXP v_uSEXP, SEXP v_dSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type S0(S0SEXP);
    Rcpp::traits::input_parameter< double >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type u(uSEXP);
    Rcpp::traits::input_parameter< double >::type d(dSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type v_u(v_uSEXP);
    Rcpp::traits::input_parameter< double >::type v_d(v_dSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(price_european_call_cpp(S0, K, r, u, d, lambda, v_u, v_d, n));
    return rcpp_result_gen;
END_RCPP
}
// price_european_put_cpp
double price_european_put_cpp(double S0, double K, double r, double u, double d, double lambda, double v_u, double v_d, int n);
RcppExport SEXP _AsianOption_price_european_put_cpp(SEXP S0SEXP, SEXP KSEXP, SEXP rSEXP, SEXP uSEXP, SEXP dSEXP, SEXP lambdaSEXP, SEXP v_uSEXP, SEXP v_dSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type S0(S0SEXP);
    Rcpp::traits::input_parameter< double >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type u(uSEXP);
    Rcpp::traits::input_parameter< double >::type d(dSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type v_u(v_uSEXP);
    Rcpp::traits::input_parameter< double >::type v_d(v_dSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(price_european_put_cpp(S0, K, r, u, d, lambda, v_u, v_d, n));
    return rcpp_result_gen;
END_RCPP
}
// generate_all_paths
std::vector<std::vector<int>> generate_all_paths(int n);
RcppExport SEXP _AsianOption_generate_all_paths(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_all_paths(n));
    return rcpp_result_gen;
END_RCPP
}
// price_geometric_asian_cpp
double price_geometric_asian_cpp(double S0, double K, double r, double u, double d, double lambda, double v_u, double v_d, int n, std::string option_type);
RcppExport SEXP _AsianOption_price_geometric_asian_cpp(SEXP S0SEXP, SEXP KSEXP, SEXP rSEXP, SEXP uSEXP, SEXP dSEXP, SEXP lambdaSEXP, SEXP v_uSEXP, SEXP v_dSEXP, SEXP nSEXP, SEXP option_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type S0(S0SEXP);
    Rcpp::traits::input_parameter< double >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type u(uSEXP);
    Rcpp::traits::input_parameter< double >::type d(dSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type v_u(v_uSEXP);
    Rcpp::traits::input_parameter< double >::type v_d(v_dSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< std::string >::type option_type(option_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(price_geometric_asian_cpp(S0, K, r, u, d, lambda, v_u, v_d, n, option_type));
    return rcpp_result_gen;
END_RCPP
}
// price_geometric_asian_transient_cpp
double price_geometric_asian_transient_cpp(double S0, double K, double r, double u, double d, double lambda_P, double lambda_T, double alpha, double psi, Rcpp::NumericVector volumes, std::string option_type);
RcppExport SEXP _AsianOption_price_geometric_asian_transient_cpp(SEXP S0SEXP, SEXP KSEXP, SEXP rSEXP, SEXP uSEXP, SEXP dSEXP, SEXP lambda_PSEXP, SEXP lambda_TSEXP, SEXP alphaSEXP, SEXP psiSEXP, SEXP volumesSEXP, SEXP option_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type S0(S0SEXP);
    Rcpp::traits::input_parameter< double >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type u(uSEXP);
    Rcpp::traits::input_parameter< double >::type d(dSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_P(lambda_PSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_T(lambda_TSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type psi(psiSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type volumes(volumesSEXP);
    Rcpp::traits::input_parameter< std::string >::type option_type(option_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(price_geometric_asian_transient_cpp(S0, K, r, u, d, lambda_P, lambda_T, alpha, psi, volumes, option_type));
    return rcpp_result_gen;
END_RCPP
}
// hjb_arithmetic_value_cpp
Rcpp::List hjb_arithmetic_value_cpp(double S0, double K, double T, int N, double sigma, double r_cont, double kappa, double lambda_bar_T, double lambda_bar_P, double k_A, double k_B, double psi_cost, Rcpp::NumericVector eta_vec, double p, double I0, Rcpp::NumericVector control_set, int n_logS, int n_I, int n_Y, double payoff_sign, bool store_policy);
RcppExport SEXP _AsianOption_hjb_arithmetic_value_cpp(SEXP S0SEXP, SEXP KSEXP, SEXP TSEXP, SEXP NSEXP, SEXP sigmaSEXP, SEXP r_contSEXP, SEXP kappaSEXP, SEXP lambda_bar_TSEXP, SEXP lambda_bar_PSEXP, SEXP k_ASEXP, SEXP k_BSEXP, SEXP psi_costSEXP, SEXP eta_vecSEXP, SEXP pSEXP, SEXP I0SEXP, SEXP control_setSEXP, SEXP n_logSSEXP, SEXP n_ISEXP, SEXP n_YSEXP, SEXP payoff_signSEXP, SEXP store_policySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type S0(S0SEXP);
    Rcpp::traits::input_parameter< double >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type T(TSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type r_cont(r_contSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_bar_T(lambda_bar_TSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_bar_P(lambda_bar_PSEXP);
    Rcpp::traits::input_parameter< double >::type k_A(k_ASEXP);
    Rcpp::traits::input_parameter< double >::type k_B(k_BSEXP);
    Rcpp::traits::input_parameter< double >::type psi_cost(psi_costSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type eta_vec(eta_vecSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type I0(I0SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type control_set(control_setSEXP);
    Rcpp::traits::input_parameter< int >::type n_logS(n_logSSEXP);
    Rcpp::traits::input_parameter< int >::type n_I(n_ISEXP);
    Rcpp::traits::input_parameter< int >::type n_Y(n_YSEXP);
    Rcpp::traits::input_parameter< double >::type payoff_sign(payoff_signSEXP);
    Rcpp::traits::input_parameter< bool >::type store_policy(store_policySEXP);
    rcpp_result_gen = Rcpp::wrap(hjb_arithmetic_value_cpp(S0, K, T, N, sigma, r_cont, kappa, lambda_bar_T, lambda_bar_P, k_A, k_B, psi_cost, eta_vec, p, I0, control_set, n_logS, n_I, n_Y, payoff_sign, store_policy));
    return rcpp_result_gen;
END_RCPP
}
// hjb_geometric_value_cpp
Rcpp::List hjb_geometric_value_cpp(double S0, double K, double T, int N, double sigma, double r_cont, double kappa, double lambda_bar_T, double lambda_bar_P, double k_A, double k_B, double psi_cost, Rcpp::NumericVector eta_vec, double p, double I0, Rcpp::NumericVector control_set, int n_logS, int n_I, int n_Y, double payoff_sign, bool store_policy);
RcppExport SEXP _AsianOption_hjb_geometric_value_cpp(SEXP S0SEXP, SEXP KSEXP, SEXP TSEXP, SEXP NSEXP, SEXP sigmaSEXP, SEXP r_contSEXP, SEXP kappaSEXP, SEXP lambda_bar_TSEXP, SEXP lambda_bar_PSEXP, SEXP k_ASEXP, SEXP k_BSEXP, SEXP psi_costSEXP, SEXP eta_vecSEXP, SEXP pSEXP, SEXP I0SEXP, SEXP control_setSEXP, SEXP n_logSSEXP, SEXP n_ISEXP, SEXP n_YSEXP, SEXP payoff_signSEXP, SEXP store_policySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type S0(S0SEXP);
    Rcpp::traits::input_parameter< double >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type T(TSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type r_cont(r_contSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_bar_T(lambda_bar_TSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_bar_P(lambda_bar_PSEXP);
    Rcpp::traits::input_parameter< double >::type k_A(k_ASEXP);
    Rcpp::traits::input_parameter< double >::type k_B(k_BSEXP);
    Rcpp::traits::input_parameter< double >::type psi_cost(psi_costSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type eta_vec(eta_vecSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type I0(I0SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type control_set(control_setSEXP);
    Rcpp::traits::input_parameter< int >::type n_logS(n_logSSEXP);
    Rcpp::traits::input_parameter< int >::type n_I(n_ISEXP);
    Rcpp::traits::input_parameter< int >::type n_Y(n_YSEXP);
    Rcpp::traits::input_parameter< double >::type payoff_sign(payoff_signSEXP);
    Rcpp::traits::input_parameter< bool >::type store_policy(store_policySEXP);
    rcpp_result_gen = Rcpp::wrap(hjb_geometric_value_cpp(S0, K, T, N, sigma, r_cont, kappa, lambda_bar_T, lambda_bar_P, k_A, k_B, psi_cost, eta_vec, p, I0, control_set, n_logS, n_I, n_Y, payoff_sign, store_policy));
    return rcpp_result_gen;
END_RCPP
}
// hjb_arithmetic_quotes_cpp
Rcpp::List hjb_arithmetic_quotes_cpp(double S0, double K, double T, int N, double sigma, double r_cont, double kappa, double lambda_bar_T, double lambda_bar_P, double k_A, double k_B, double psi_cost, Rcpp::NumericVector eta_vec, double p, double I0, Rcpp::NumericVector control_set, int n_logS, int n_I, int n_Y);
RcppExport SEXP _AsianOption_hjb_arithmetic_quotes_cpp(SEXP S0SEXP, SEXP KSEXP, SEXP TSEXP, SEXP NSEXP, SEXP sigmaSEXP, SEXP r_contSEXP, SEXP kappaSEXP, SEXP lambda_bar_TSEXP, SEXP lambda_bar_PSEXP, SEXP k_ASEXP, SEXP k_BSEXP, SEXP psi_costSEXP, SEXP eta_vecSEXP, SEXP pSEXP, SEXP I0SEXP, SEXP control_setSEXP, SEXP n_logSSEXP, SEXP n_ISEXP, SEXP n_YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type S0(S0SEXP);
    Rcpp::traits::input_parameter< double >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type T(TSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type r_cont(r_contSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_bar_T(lambda_bar_TSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_bar_P(lambda_bar_PSEXP);
    Rcpp::traits::input_parameter< double >::type k_A(k_ASEXP);
    Rcpp::traits::input_parameter< double >::type k_B(k_BSEXP);
    Rcpp::traits::input_parameter< double >::type psi_cost(psi_costSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type eta_vec(eta_vecSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type I0(I0SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type control_set(control_setSEXP);
    Rcpp::traits::input_parameter< int >::type n_logS(n_logSSEXP);
    Rcpp::traits::input_parameter< int >::type n_I(n_ISEXP);
    Rcpp::traits::input_parameter< int >::type n_Y(n_YSEXP);
    rcpp_result_gen = Rcpp::wrap(hjb_arithmetic_quotes_cpp(S0, K, T, N, sigma, r_cont, kappa, lambda_bar_T, lambda_bar_P, k_A, k_B, psi_cost, eta_vec, p, I0, control_set, n_logS, n_I, n_Y));
    return rcpp_result_gen;
END_RCPP
}
// hjb_arithmetic_quotes_with_policy_cpp
Rcpp::List hjb_arithmetic_quotes_with_policy_cpp(double S0, double K, double T, int N, double sigma, double r_cont, double kappa, double lambda_bar_T, double lambda_bar_P, double k_A, double k_B, double psi_cost, Rcpp::NumericVector eta_vec, double p, double I0, Rcpp::NumericVector control_set, int n_logS, int n_I, int n_Y);
RcppExport SEXP _AsianOption_hjb_arithmetic_quotes_with_policy_cpp(SEXP S0SEXP, SEXP KSEXP, SEXP TSEXP, SEXP NSEXP, SEXP sigmaSEXP, SEXP r_contSEXP, SEXP kappaSEXP, SEXP lambda_bar_TSEXP, SEXP lambda_bar_PSEXP, SEXP k_ASEXP, SEXP k_BSEXP, SEXP psi_costSEXP, SEXP eta_vecSEXP, SEXP pSEXP, SEXP I0SEXP, SEXP control_setSEXP, SEXP n_logSSEXP, SEXP n_ISEXP, SEXP n_YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type S0(S0SEXP);
    Rcpp::traits::input_parameter< double >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type T(TSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type r_cont(r_contSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_bar_T(lambda_bar_TSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_bar_P(lambda_bar_PSEXP);
    Rcpp::traits::input_parameter< double >::type k_A(k_ASEXP);
    Rcpp::traits::input_parameter< double >::type k_B(k_BSEXP);
    Rcpp::traits::input_parameter< double >::type psi_cost(psi_costSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type eta_vec(eta_vecSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type I0(I0SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type control_set(control_setSEXP);
    Rcpp::traits::input_parameter< int >::type n_logS(n_logSSEXP);
    Rcpp::traits::input_parameter< int >::type n_I(n_ISEXP);
    Rcpp::traits::input_parameter< int >::type n_Y(n_YSEXP);
    rcpp_result_gen = Rcpp::wrap(hjb_arithmetic_quotes_with_policy_cpp(S0, K, T, N, sigma, r_cont, kappa, lambda_bar_T, lambda_bar_P, k_A, k_B, psi_cost, eta_vec, p, I0, control_set, n_logS, n_I, n_Y));
    return rcpp_result_gen;
END_RCPP
}
// hjb_geometric_quotes_with_policy_cpp
Rcpp::List hjb_geometric_quotes_with_policy_cpp(double S0, double K, double T, int N, double sigma, double r_cont, double kappa, double lambda_bar_T, double lambda_bar_P, double k_A, double k_B, double psi_cost, Rcpp::NumericVector eta_vec, double p, double I0, Rcpp::NumericVector control_set, int n_logS, int n_I, int n_Y);
RcppExport SEXP _AsianOption_hjb_geometric_quotes_with_policy_cpp(SEXP S0SEXP, SEXP KSEXP, SEXP TSEXP, SEXP NSEXP, SEXP sigmaSEXP, SEXP r_contSEXP, SEXP kappaSEXP, SEXP lambda_bar_TSEXP, SEXP lambda_bar_PSEXP, SEXP k_ASEXP, SEXP k_BSEXP, SEXP psi_costSEXP, SEXP eta_vecSEXP, SEXP pSEXP, SEXP I0SEXP, SEXP control_setSEXP, SEXP n_logSSEXP, SEXP n_ISEXP, SEXP n_YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type S0(S0SEXP);
    Rcpp::traits::input_parameter< double >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type T(TSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type r_cont(r_contSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_bar_T(lambda_bar_TSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_bar_P(lambda_bar_PSEXP);
    Rcpp::traits::input_parameter< double >::type k_A(k_ASEXP);
    Rcpp::traits::input_parameter< double >::type k_B(k_BSEXP);
    Rcpp::traits::input_parameter< double >::type psi_cost(psi_costSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type eta_vec(eta_vecSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type I0(I0SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type control_set(control_setSEXP);
    Rcpp::traits::input_parameter< int >::type n_logS(n_logSSEXP);
    Rcpp::traits::input_parameter< int >::type n_I(n_ISEXP);
    Rcpp::traits::input_parameter< int >::type n_Y(n_YSEXP);
    rcpp_result_gen = Rcpp::wrap(hjb_geometric_quotes_with_policy_cpp(S0, K, T, N, sigma, r_cont, kappa, lambda_bar_T, lambda_bar_P, k_A, k_B, psi_cost, eta_vec, p, I0, control_set, n_logS, n_I, n_Y));
    return rcpp_result_gen;
END_RCPP
}
// hjb_geometric_quotes_cpp
Rcpp::List hjb_geometric_quotes_cpp(double S0, double K, double T, int N, double sigma, double r_cont, double kappa, double lambda_bar_T, double lambda_bar_P, double k_A, double k_B, double psi_cost, Rcpp::NumericVector eta_vec, double p, double I0, Rcpp::NumericVector control_set, int n_logS, int n_I, int n_Y);
RcppExport SEXP _AsianOption_hjb_geometric_quotes_cpp(SEXP S0SEXP, SEXP KSEXP, SEXP TSEXP, SEXP NSEXP, SEXP sigmaSEXP, SEXP r_contSEXP, SEXP kappaSEXP, SEXP lambda_bar_TSEXP, SEXP lambda_bar_PSEXP, SEXP k_ASEXP, SEXP k_BSEXP, SEXP psi_costSEXP, SEXP eta_vecSEXP, SEXP pSEXP, SEXP I0SEXP, SEXP control_setSEXP, SEXP n_logSSEXP, SEXP n_ISEXP, SEXP n_YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type S0(S0SEXP);
    Rcpp::traits::input_parameter< double >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type T(TSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type r_cont(r_contSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_bar_T(lambda_bar_TSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_bar_P(lambda_bar_PSEXP);
    Rcpp::traits::input_parameter< double >::type k_A(k_ASEXP);
    Rcpp::traits::input_parameter< double >::type k_B(k_BSEXP);
    Rcpp::traits::input_parameter< double >::type psi_cost(psi_costSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type eta_vec(eta_vecSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type I0(I0SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type control_set(control_setSEXP);
    Rcpp::traits::input_parameter< int >::type n_logS(n_logSSEXP);
    Rcpp::traits::input_parameter< int >::type n_I(n_ISEXP);
    Rcpp::traits::input_parameter< int >::type n_Y(n_YSEXP);
    rcpp_result_gen = Rcpp::wrap(hjb_geometric_quotes_cpp(S0, K, T, N, sigma, r_cont, kappa, lambda_bar_T, lambda_bar_P, k_A, k_B, psi_cost, eta_vec, p, I0, control_set, n_logS, n_I, n_Y));
    return rcpp_result_gen;
END_RCPP
}
// indiff_branch_probs_cpp
Rcpp::NumericVector indiff_branch_probs_cpp(double rho);
RcppExport SEXP _AsianOption_indiff_branch_probs_cpp(SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(indiff_branch_probs_cpp(rho));
    return rcpp_result_gen;
END_RCPP
}
// indiff_discount_helpers_cpp
Rcpp::List indiff_discount_helpers_cpp(double r_cont, double T_mat, int N);
RcppExport SEXP _AsianOption_indiff_discount_helpers_cpp(SEXP r_contSEXP, SEXP T_matSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type r_cont(r_contSEXP);
    Rcpp::traits::input_parameter< double >::type T_mat(T_matSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(indiff_discount_helpers_cpp(r_cont, T_mat, N));
    return rcpp_result_gen;
END_RCPP
}
// indiff_payoff_cpp
double indiff_payoff_cpp(double a, double S0, double K, double T_mat, int asian_type, int option_type, double phi_cap);
RcppExport SEXP _AsianOption_indiff_payoff_cpp(SEXP aSEXP, SEXP S0SEXP, SEXP KSEXP, SEXP T_matSEXP, SEXP asian_typeSEXP, SEXP option_typeSEXP, SEXP phi_capSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type S0(S0SEXP);
    Rcpp::traits::input_parameter< double >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type T_mat(T_matSEXP);
    Rcpp::traits::input_parameter< int >::type asian_type(asian_typeSEXP);
    Rcpp::traits::input_parameter< int >::type option_type(option_typeSEXP);
    Rcpp::traits::input_parameter< double >::type phi_cap(phi_capSEXP);
    rcpp_result_gen = Rcpp::wrap(indiff_payoff_cpp(a, S0, K, T_mat, asian_type, option_type, phi_cap));
    return rcpp_result_gen;
END_RCPP
}
// indiff_has_openmp_cpp
bool indiff_has_openmp_cpp();
RcppExport SEXP _AsianOption_indiff_has_openmp_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(indiff_has_openmp_cpp());
    return rcpp_result_gen;
END_RCPP
}
// indiff_bellman_engine_cpp
Rcpp::List indiff_bellman_engine_cpp(double S0, double K, double T_mat, int N, Rcpp::NumericVector mu_vec, double sigma, double r_cont, double lambda_I, double kappa_I, Rcpp::NumericVector eta_vec, double rho, double lambda_bar_T, double lambda_bar_P, double kappa_J, double k_A, double k_B, double psi_cost, double gamma_ra, double Gamma_Q, double Gamma_J, double Q_bar, double phi_cap, double n_opt, double I0, double Q0, double J0, Rcpp::NumericVector control_set, int n_logS, int n_I, int n_Q, int n_J, int n_R, int asian_type, int option_type, int theta, int accum_rule, double accum_sd, int grid_drift, bool store_policy, int n_threads, int engine_mode, bool verbose);
RcppExport SEXP _AsianOption_indiff_bellman_engine_cpp(SEXP S0SEXP, SEXP KSEXP, SEXP T_matSEXP, SEXP NSEXP, SEXP mu_vecSEXP, SEXP sigmaSEXP, SEXP r_contSEXP, SEXP lambda_ISEXP, SEXP kappa_ISEXP, SEXP eta_vecSEXP, SEXP rhoSEXP, SEXP lambda_bar_TSEXP, SEXP lambda_bar_PSEXP, SEXP kappa_JSEXP, SEXP k_ASEXP, SEXP k_BSEXP, SEXP psi_costSEXP, SEXP gamma_raSEXP, SEXP Gamma_QSEXP, SEXP Gamma_JSEXP, SEXP Q_barSEXP, SEXP phi_capSEXP, SEXP n_optSEXP, SEXP I0SEXP, SEXP Q0SEXP, SEXP J0SEXP, SEXP control_setSEXP, SEXP n_logSSEXP, SEXP n_ISEXP, SEXP n_QSEXP, SEXP n_JSEXP, SEXP n_RSEXP, SEXP asian_typeSEXP, SEXP option_typeSEXP, SEXP thetaSEXP, SEXP accum_ruleSEXP, SEXP accum_sdSEXP, SEXP grid_driftSEXP, SEXP store_policySEXP, SEXP n_threadsSEXP, SEXP engine_modeSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type S0(S0SEXP);
    Rcpp::traits::input_parameter< double >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type T_mat(T_matSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mu_vec(mu_vecSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type r_cont(r_contSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_I(lambda_ISEXP);
    Rcpp::traits::input_parameter< double >::type kappa_I(kappa_ISEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type eta_vec(eta_vecSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_bar_T(lambda_bar_TSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_bar_P(lambda_bar_PSEXP);
    Rcpp::traits::input_parameter< double >::type kappa_J(kappa_JSEXP);
    Rcpp::traits::input_parameter< double >::type k_A(k_ASEXP);
    Rcpp::traits::input_parameter< double >::type k_B(k_BSEXP);
    Rcpp::traits::input_parameter< double >::type psi_cost(psi_costSEXP);
    Rcpp::traits::input_parameter< double >::type gamma_ra(gamma_raSEXP);
    Rcpp::traits::input_parameter< double >::type Gamma_Q(Gamma_QSEXP);
    Rcpp::traits::input_parameter< double >::type Gamma_J(Gamma_JSEXP);
    Rcpp::traits::input_parameter< double >::type Q_bar(Q_barSEXP);
    Rcpp::traits::input_parameter< double >::type phi_cap(phi_capSEXP);
    Rcpp::traits::input_parameter< double >::type n_opt(n_optSEXP);
    Rcpp::traits::input_parameter< double >::type I0(I0SEXP);
    Rcpp::traits::input_parameter< double >::type Q0(Q0SEXP);
    Rcpp::traits::input_parameter< double >::type J0(J0SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type control_set(control_setSEXP);
    Rcpp::traits::input_parameter< int >::type n_logS(n_logSSEXP);
    Rcpp::traits::input_parameter< int >::type n_I(n_ISEXP);
    Rcpp::traits::input_parameter< int >::type n_Q(n_QSEXP);
    Rcpp::traits::input_parameter< int >::type n_J(n_JSEXP);
    Rcpp::traits::input_parameter< int >::type n_R(n_RSEXP);
    Rcpp::traits::input_parameter< int >::type asian_type(asian_typeSEXP);
    Rcpp::traits::input_parameter< int >::type option_type(option_typeSEXP);
    Rcpp::traits::input_parameter< int >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type accum_rule(accum_ruleSEXP);
    Rcpp::traits::input_parameter< double >::type accum_sd(accum_sdSEXP);
    Rcpp::traits::input_parameter< int >::type grid_drift(grid_driftSEXP);
    Rcpp::traits::input_parameter< bool >::type store_policy(store_policySEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type engine_mode(engine_modeSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(indiff_bellman_engine_cpp(S0, K, T_mat, N, mu_vec, sigma, r_cont, lambda_I, kappa_I, eta_vec, rho, lambda_bar_T, lambda_bar_P, kappa_J, k_A, k_B, psi_cost, gamma_ra, Gamma_Q, Gamma_J, Q_bar, phi_cap, n_opt, I0, Q0, J0, control_set, n_logS, n_I, n_Q, n_J, n_R, asian_type, option_type, theta, accum_rule, accum_sd, grid_drift, store_policy, n_threads, engine_mode, verbose));
    return rcpp_result_gen;
END_RCPP
}
// price_kemna_vorst_arithmetic_cpp
List price_kemna_vorst_arithmetic_cpp(double S0, double K, double r, double sigma, double T0, double T_mat, int n, int M, std::string option_type, bool use_control_variate, int seed);
RcppExport SEXP _AsianOption_price_kemna_vorst_arithmetic_cpp(SEXP S0SEXP, SEXP KSEXP, SEXP rSEXP, SEXP sigmaSEXP, SEXP T0SEXP, SEXP T_matSEXP, SEXP nSEXP, SEXP MSEXP, SEXP option_typeSEXP, SEXP use_control_variateSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type S0(S0SEXP);
    Rcpp::traits::input_parameter< double >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type T0(T0SEXP);
    Rcpp::traits::input_parameter< double >::type T_mat(T_matSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< std::string >::type option_type(option_typeSEXP);
    Rcpp::traits::input_parameter< bool >::type use_control_variate(use_control_variateSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(price_kemna_vorst_arithmetic_cpp(S0, K, r, sigma, T0, T_mat, n, M, option_type, use_control_variate, seed));
    return rcpp_result_gen;
END_RCPP
}
// price_kemna_vorst_arithmetic_binomial_cpp
List price_kemna_vorst_arithmetic_binomial_cpp(double S0, double K, double r, double u, double d, int n, int M, std::string option_type, bool use_control_variate, int seed);
RcppExport SEXP _AsianOption_price_kemna_vorst_arithmetic_binomial_cpp(SEXP S0SEXP, SEXP KSEXP, SEXP rSEXP, SEXP uSEXP, SEXP dSEXP, SEXP nSEXP, SEXP MSEXP, SEXP option_typeSEXP, SEXP use_control_variateSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type S0(S0SEXP);
    Rcpp::traits::input_parameter< double >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type u(uSEXP);
    Rcpp::traits::input_parameter< double >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< std::string >::type option_type(option_typeSEXP);
    Rcpp::traits::input_parameter< bool >::type use_control_variate(use_control_variateSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(price_kemna_vorst_arithmetic_binomial_cpp(S0, K, r, u, d, n, M, option_type, use_control_variate, seed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_AsianOption_price_arithmetic_asian_diffusion_mc_cpp", (DL_FUNC) &_AsianOption_price_arithmetic_asian_diffusion_mc_cpp, 15},
    {"_AsianOption_arithmetic_asian_bounds_cpp", (DL_FUNC) &_AsianOption_arithmetic_asian_bounds_cpp, 10},
    {"_AsianOption_arithmetic_asian_bounds_extended_cpp", (DL_FUNC) &_AsianOption_arithmetic_asian_bounds_extended_cpp, 11},
    {"_AsianOption_arithmetic_asian_bounds_transient_cpp", (DL_FUNC) &_AsianOption_arithmetic_asian_bounds_transient_cpp, 12},
    {"_AsianOption_price_european_call_cpp", (DL_FUNC) &_AsianOption_price_european_call_cpp, 9},
    {"_AsianOption_price_european_put_cpp", (DL_FUNC) &_AsianOption_price_european_put_cpp, 9},
    {"_AsianOption_generate_all_paths", (DL_FUNC) &_AsianOption_generate_all_paths, 1},
    {"_AsianOption_price_geometric_asian_cpp", (DL_FUNC) &_AsianOption_price_geometric_asian_cpp, 10},
    {"_AsianOption_price_geometric_asian_transient_cpp", (DL_FUNC) &_AsianOption_price_geometric_asian_transient_cpp, 11},
    {"_AsianOption_hjb_arithmetic_value_cpp", (DL_FUNC) &_AsianOption_hjb_arithmetic_value_cpp, 21},
    {"_AsianOption_hjb_geometric_value_cpp", (DL_FUNC) &_AsianOption_hjb_geometric_value_cpp, 21},
    {"_AsianOption_hjb_arithmetic_quotes_cpp", (DL_FUNC) &_AsianOption_hjb_arithmetic_quotes_cpp, 19},
    {"_AsianOption_hjb_arithmetic_quotes_with_policy_cpp", (DL_FUNC) &_AsianOption_hjb_arithmetic_quotes_with_policy_cpp, 19},
    {"_AsianOption_hjb_geometric_quotes_with_policy_cpp", (DL_FUNC) &_AsianOption_hjb_geometric_quotes_with_policy_cpp, 19},
    {"_AsianOption_hjb_geometric_quotes_cpp", (DL_FUNC) &_AsianOption_hjb_geometric_quotes_cpp, 19},
    {"_AsianOption_indiff_branch_probs_cpp", (DL_FUNC) &_AsianOption_indiff_branch_probs_cpp, 1},
    {"_AsianOption_indiff_discount_helpers_cpp", (DL_FUNC) &_AsianOption_indiff_discount_helpers_cpp, 3},
    {"_AsianOption_indiff_payoff_cpp", (DL_FUNC) &_AsianOption_indiff_payoff_cpp, 7},
    {"_AsianOption_indiff_has_openmp_cpp", (DL_FUNC) &_AsianOption_indiff_has_openmp_cpp, 0},
    {"_AsianOption_indiff_bellman_engine_cpp", (DL_FUNC) &_AsianOption_indiff_bellman_engine_cpp, 42},
    {"_AsianOption_price_kemna_vorst_arithmetic_cpp", (DL_FUNC) &_AsianOption_price_kemna_vorst_arithmetic_cpp, 11},
    {"_AsianOption_price_kemna_vorst_arithmetic_binomial_cpp", (DL_FUNC) &_AsianOption_price_kemna_vorst_arithmetic_binomial_cpp, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_AsianOption(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
