// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// arithmetic_asian_bounds_cpp
Rcpp::List arithmetic_asian_bounds_cpp(double S0, double K, double r, double u, double d, double lambda, double v_u, double v_d, int n, std::string option_type);
RcppExport SEXP _AsianOption_arithmetic_asian_bounds_cpp(SEXP S0SEXP, SEXP KSEXP, SEXP rSEXP, SEXP uSEXP, SEXP dSEXP, SEXP lambdaSEXP, SEXP v_uSEXP, SEXP v_dSEXP, SEXP nSEXP, SEXP option_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type S0(S0SEXP);
    Rcpp::traits::input_parameter< double >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type u(uSEXP);
    Rcpp::traits::input_parameter< double >::type d(dSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type v_u(v_uSEXP);
    Rcpp::traits::input_parameter< double >::type v_d(v_dSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< std::string >::type option_type(option_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(arithmetic_asian_bounds_cpp(S0, K, r, u, d, lambda, v_u, v_d, n, option_type));
    return rcpp_result_gen;
END_RCPP
}
// arithmetic_asian_bounds_extended_cpp
Rcpp::List arithmetic_asian_bounds_extended_cpp(double S0, double K, double r, double u, double d, double lambda, double v_u, double v_d, int n, bool compute_path_specific, int max_sample_size, double sample_fraction, std::string option_type);
RcppExport SEXP _AsianOption_arithmetic_asian_bounds_extended_cpp(SEXP S0SEXP, SEXP KSEXP, SEXP rSEXP, SEXP uSEXP, SEXP dSEXP, SEXP lambdaSEXP, SEXP v_uSEXP, SEXP v_dSEXP, SEXP nSEXP, SEXP compute_path_specificSEXP, SEXP max_sample_sizeSEXP, SEXP sample_fractionSEXP, SEXP option_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type S0(S0SEXP);
    Rcpp::traits::input_parameter< double >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type u(uSEXP);
    Rcpp::traits::input_parameter< double >::type d(dSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type v_u(v_uSEXP);
    Rcpp::traits::input_parameter< double >::type v_d(v_dSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< bool >::type compute_path_specific(compute_path_specificSEXP);
    Rcpp::traits::input_parameter< int >::type max_sample_size(max_sample_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type sample_fraction(sample_fractionSEXP);
    Rcpp::traits::input_parameter< std::string >::type option_type(option_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(arithmetic_asian_bounds_extended_cpp(S0, K, r, u, d, lambda, v_u, v_d, n, compute_path_specific, max_sample_size, sample_fraction, option_type));
    return rcpp_result_gen;
END_RCPP
}
// price_european_call_cpp
double price_european_call_cpp(double S0, double K, double r, double u, double d, double lambda, double v_u, double v_d, int n);
RcppExport SEXP _AsianOption_price_european_call_cpp(SEXP S0SEXP, SEXP KSEXP, SEXP rSEXP, SEXP uSEXP, SEXP dSEXP, SEXP lambdaSEXP, SEXP v_uSEXP, SEXP v_dSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type S0(S0SEXP);
    Rcpp::traits::input_parameter< double >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type u(uSEXP);
    Rcpp::traits::input_parameter< double >::type d(dSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type v_u(v_uSEXP);
    Rcpp::traits::input_parameter< double >::type v_d(v_dSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(price_european_call_cpp(S0, K, r, u, d, lambda, v_u, v_d, n));
    return rcpp_result_gen;
END_RCPP
}
// price_european_put_cpp
double price_european_put_cpp(double S0, double K, double r, double u, double d, double lambda, double v_u, double v_d, int n);
RcppExport SEXP _AsianOption_price_european_put_cpp(SEXP S0SEXP, SEXP KSEXP, SEXP rSEXP, SEXP uSEXP, SEXP dSEXP, SEXP lambdaSEXP, SEXP v_uSEXP, SEXP v_dSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type S0(S0SEXP);
    Rcpp::traits::input_parameter< double >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type u(uSEXP);
    Rcpp::traits::input_parameter< double >::type d(dSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type v_u(v_uSEXP);
    Rcpp::traits::input_parameter< double >::type v_d(v_dSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(price_european_put_cpp(S0, K, r, u, d, lambda, v_u, v_d, n));
    return rcpp_result_gen;
END_RCPP
}
// price_geometric_asian_cpp
double price_geometric_asian_cpp(double S0, double K, double r, double u, double d, double lambda, double v_u, double v_d, int n, std::string option_type);
RcppExport SEXP _AsianOption_price_geometric_asian_cpp(SEXP S0SEXP, SEXP KSEXP, SEXP rSEXP, SEXP uSEXP, SEXP dSEXP, SEXP lambdaSEXP, SEXP v_uSEXP, SEXP v_dSEXP, SEXP nSEXP, SEXP option_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type S0(S0SEXP);
    Rcpp::traits::input_parameter< double >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type u(uSEXP);
    Rcpp::traits::input_parameter< double >::type d(dSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type v_u(v_uSEXP);
    Rcpp::traits::input_parameter< double >::type v_d(v_dSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< std::string >::type option_type(option_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(price_geometric_asian_cpp(S0, K, r, u, d, lambda, v_u, v_d, n, option_type));
    return rcpp_result_gen;
END_RCPP
}
// price_geometric_asian_mc_cpp
Rcpp::List price_geometric_asian_mc_cpp(double S0, double K, double r, double u, double d, double lambda, double v_u, double v_d, int n, int n_simulations, std::string option_type, int seed);
RcppExport SEXP _AsianOption_price_geometric_asian_mc_cpp(SEXP S0SEXP, SEXP KSEXP, SEXP rSEXP, SEXP uSEXP, SEXP dSEXP, SEXP lambdaSEXP, SEXP v_uSEXP, SEXP v_dSEXP, SEXP nSEXP, SEXP n_simulationsSEXP, SEXP option_typeSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type S0(S0SEXP);
    Rcpp::traits::input_parameter< double >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type u(uSEXP);
    Rcpp::traits::input_parameter< double >::type d(dSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type v_u(v_uSEXP);
    Rcpp::traits::input_parameter< double >::type v_d(v_dSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type n_simulations(n_simulationsSEXP);
    Rcpp::traits::input_parameter< std::string >::type option_type(option_typeSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(price_geometric_asian_mc_cpp(S0, K, r, u, d, lambda, v_u, v_d, n, n_simulations, option_type, seed));
    return rcpp_result_gen;
END_RCPP
}
// price_kemna_vorst_arithmetic_cpp
List price_kemna_vorst_arithmetic_cpp(double S0, double K, double r, double sigma, double T0, double T, int n, int M, std::string option_type, bool use_control_variate, int seed);
RcppExport SEXP _AsianOption_price_kemna_vorst_arithmetic_cpp(SEXP S0SEXP, SEXP KSEXP, SEXP rSEXP, SEXP sigmaSEXP, SEXP T0SEXP, SEXP TSEXP, SEXP nSEXP, SEXP MSEXP, SEXP option_typeSEXP, SEXP use_control_variateSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type S0(S0SEXP);
    Rcpp::traits::input_parameter< double >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type T0(T0SEXP);
    Rcpp::traits::input_parameter< double >::type T(TSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< std::string >::type option_type(option_typeSEXP);
    Rcpp::traits::input_parameter< bool >::type use_control_variate(use_control_variateSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(price_kemna_vorst_arithmetic_cpp(S0, K, r, sigma, T0, T, n, M, option_type, use_control_variate, seed));
    return rcpp_result_gen;
END_RCPP
}
// price_kemna_vorst_arithmetic_binomial_cpp
List price_kemna_vorst_arithmetic_binomial_cpp(double S0, double K, double r, double u, double d, int n, int M, std::string option_type, bool use_control_variate, int seed);
RcppExport SEXP _AsianOption_price_kemna_vorst_arithmetic_binomial_cpp(SEXP S0SEXP, SEXP KSEXP, SEXP rSEXP, SEXP uSEXP, SEXP dSEXP, SEXP nSEXP, SEXP MSEXP, SEXP option_typeSEXP, SEXP use_control_variateSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type S0(S0SEXP);
    Rcpp::traits::input_parameter< double >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type u(uSEXP);
    Rcpp::traits::input_parameter< double >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< std::string >::type option_type(option_typeSEXP);
    Rcpp::traits::input_parameter< bool >::type use_control_variate(use_control_variateSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(price_kemna_vorst_arithmetic_binomial_cpp(S0, K, r, u, d, n, M, option_type, use_control_variate, seed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_AsianOption_arithmetic_asian_bounds_cpp", (DL_FUNC) &_AsianOption_arithmetic_asian_bounds_cpp, 10},
    {"_AsianOption_arithmetic_asian_bounds_extended_cpp", (DL_FUNC) &_AsianOption_arithmetic_asian_bounds_extended_cpp, 13},
    {"_AsianOption_price_european_call_cpp", (DL_FUNC) &_AsianOption_price_european_call_cpp, 9},
    {"_AsianOption_price_european_put_cpp", (DL_FUNC) &_AsianOption_price_european_put_cpp, 9},
    {"_AsianOption_price_geometric_asian_cpp", (DL_FUNC) &_AsianOption_price_geometric_asian_cpp, 10},
    {"_AsianOption_price_geometric_asian_mc_cpp", (DL_FUNC) &_AsianOption_price_geometric_asian_mc_cpp, 12},
    {"_AsianOption_price_kemna_vorst_arithmetic_cpp", (DL_FUNC) &_AsianOption_price_kemna_vorst_arithmetic_cpp, 11},
    {"_AsianOption_price_kemna_vorst_arithmetic_binomial_cpp", (DL_FUNC) &_AsianOption_price_kemna_vorst_arithmetic_binomial_cpp, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_AsianOption(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
