# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

arithmetic_asian_bounds_cpp <- function(S0, K, r, u, d, lambda, v_u, v_d, n, option_type = "call") {
    .Call(`_AsianOption_arithmetic_asian_bounds_cpp`, S0, K, r, u, d, lambda, v_u, v_d, n, option_type)
}

arithmetic_asian_bounds_extended_cpp <- function(S0, K, r, u, d, lambda, v_u, v_d, n, compute_path_specific = FALSE, option_type = "call") {
    .Call(`_AsianOption_arithmetic_asian_bounds_extended_cpp`, S0, K, r, u, d, lambda, v_u, v_d, n, compute_path_specific, option_type)
}

price_european_call_cpp <- function(S0, K, r, u, d, lambda, v_u, v_d, n) {
    .Call(`_AsianOption_price_european_call_cpp`, S0, K, r, u, d, lambda, v_u, v_d, n)
}

price_european_put_cpp <- function(S0, K, r, u, d, lambda, v_u, v_d, n) {
    .Call(`_AsianOption_price_european_put_cpp`, S0, K, r, u, d, lambda, v_u, v_d, n)
}

generate_all_paths <- function(n) {
    .Call(`_AsianOption_generate_all_paths`, n)
}

price_geometric_asian_cpp <- function(S0, K, r, u, d, lambda, v_u, v_d, n, option_type = "call") {
    .Call(`_AsianOption_price_geometric_asian_cpp`, S0, K, r, u, d, lambda, v_u, v_d, n, option_type)
}

price_kemna_vorst_arithmetic_cpp <- function(S0, K, r, sigma, T0, T_mat, n, M, option_type = "call", use_control_variate = TRUE, seed = 0L) {
    .Call(`_AsianOption_price_kemna_vorst_arithmetic_cpp`, S0, K, r, sigma, T0, T_mat, n, M, option_type, use_control_variate, seed)
}

price_kemna_vorst_arithmetic_binomial_cpp <- function(S0, K, r, u, d, n, M, option_type = "call", use_control_variate = TRUE, seed = 0L) {
    .Call(`_AsianOption_price_kemna_vorst_arithmetic_binomial_cpp`, S0, K, r, u, d, n, M, option_type, use_control_variate, seed)
}

