# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute Bounds for Arithmetic Asian Option
#'
#' Computes lower and upper bounds for the arithmetic Asian option (call or put)
#' using Jensen's inequality and the relationship between arithmetic
#' and geometric means.
#'
#' @param S0 Initial stock price
#' @param K Strike price
#' @param r Gross risk-free rate
#' @param u Base up factor
#' @param d Base down factor
#' @param lambda Price impact coefficient
#' @param v_u Hedging volume on up move
#' @param v_d Hedging volume on down move
#' @param n Number of time steps
#' @param option_type Type of option: "call" or "put" (default: "call")
#'
#' @return List containing:
#' \itemize{
#'   \item \code{lower_bound}: Lower bound (geometric option price)
#'   \item \code{upper_bound}: Upper bound
#'   \item \code{rho_star}: Spread parameter
#'   \item \code{EQ_G}: Expected geometric average
#' }
#'
#' @details
#' Lower bound: \eqn{V_0^A \ge V_0^G} (by AM-GM inequality)
#'
#' Upper bound: \eqn{V_0^A \le V_0^G + (rho^* - 1) \cdot E^Q(G_n) / r^n}
#'
#' where \eqn{rho^* = \exp((u_{tilde}^n - d_{tilde}^n)^2 / (4 \cdot u_{tilde}^n \cdot d_{tilde}^n))}
#'
#' @export
arithmetic_asian_bounds_cpp <- function(S0, K, r, u, d, lambda, v_u, v_d, n, option_type = "call") {
    .Call(`_AsianOption_arithmetic_asian_bounds_cpp`, S0, K, r, u, d, lambda, v_u, v_d, n, option_type)
}

#' Compute Arithmetic Asian Bounds with Path-Specific Upper Bound
#'
#' Computes lower bound (geometric option) and two upper bounds:
#' global (using rho*) and path-specific (using all 2^n paths).
#'
#' @param S0 Initial stock price
#' @param K Strike price
#' @param r Gross risk-free rate
#' @param u Base up factor
#' @param d Base down factor
#' @param lambda Price impact coefficient
#' @param v_u Hedging volume on up move
#' @param v_d Hedging volume on down move
#' @param n Number of time steps
#' @param compute_path_specific If TRUE, compute path-specific bound using all paths
#' @param option_type Type of option: "call" or "put" (default: "call")
#'
#' @return List with components:
#' \itemize{
#'   \item \code{lower_bound}: Lower bound (geometric option price)
#'   \item \code{upper_bound_global}: Global upper bound using rho*
#'   \item \code{upper_bound_path_specific}: Path-specific upper bound (NA if not computed)
#'   \item \code{rho_star}: Spread parameter
#'   \item \code{EQ_G}: Expected geometric average
#'   \item \code{V0_G}: Geometric option price (same as lower_bound)
#'   \item \code{n_paths_used}: Number of paths used (2^n if path-specific computed, 0 otherwise)
#' }
#'
#' @export
arithmetic_asian_bounds_extended_cpp <- function(S0, K, r, u, d, lambda, v_u, v_d, n, compute_path_specific = FALSE, option_type = "call") {
    .Call(`_AsianOption_arithmetic_asian_bounds_extended_cpp`, S0, K, r, u, d, lambda, v_u, v_d, n, compute_path_specific, option_type)
}

#' Price European Call Option with Price Impact
#'
#' Computes the exact price of a European call option using the
#' binomial tree model with price impact from hedging activities.
#'
#' @param S0 Initial stock price (positive)
#' @param K Strike price (positive)
#' @param r Gross risk-free rate per period (e.g., 1.05 for 5\% rate)
#' @param u Base up factor in CRR model (e.g., 1.2)
#' @param d Base down factor in CRR model (e.g., 0.8)
#' @param lambda Price impact coefficient (non-negative)
#' @param v_u Hedging volume on up move (non-negative)
#' @param v_d Hedging volume on down move (non-negative)
#' @param n Number of time steps (positive integer)
#'
#' @return European call option price
#'
#' @details
#' The function computes the European call option price using the CRR binomial
#' model with price impact. Unlike path-dependent Asian options, European options
#' only depend on the terminal stock price, allowing for efficient O(n) computation.
#'
#' The pricing formula is:
#' \deqn{V_0 = \frac{1}{r^n} \sum_{k=0}^{n} \binom{n}{k} p_{eff}^k (1-p_{eff})^{n-k} \max(0, S_n(k) - K)}
#'
#' where \eqn{S_n(k) = S_0 \tilde{u}^k \tilde{d}^{n-k}} is the stock price after k up moves.
#'
#' Price impact modifies the up and down factors:
#' - Adjusted up factor: \eqn{\tilde{u} = u \exp(\lambda v^u)}
#' - Adjusted down factor: \eqn{\tilde{d} = d \exp(-\lambda v^d)}
#' - Adjusted risk-neutral probability: \eqn{p_{adj} = \frac{r - \tilde{d}}{\tilde{u} - \tilde{d}}}
#'
#' @references
#' Cox, J. C., Ross, S. A., & Rubinstein, M. (1979). Option pricing:
#' A simplified approach. Journal of Financial Economics, 7(3), 229-263.
#' \doi{10.1016/0304-405X(79)90015-1}
#'
#' @examples
#' \dontrun{
#' # Basic example with 10 time steps
#' price_european_call_cpp(
#'   S0 = 100, K = 100, r = 1.05, u = 1.2, d = 0.8,
#'   lambda = 0.1, v_u = 1.0, v_d = 1.0, n = 10
#' )
#' }
#'
#' @export
price_european_call_cpp <- function(S0, K, r, u, d, lambda, v_u, v_d, n) {
    .Call(`_AsianOption_price_european_call_cpp`, S0, K, r, u, d, lambda, v_u, v_d, n)
}

#' Price European Put Option with Price Impact
#'
#' Computes the exact price of a European put option using the
#' binomial tree model with price impact from hedging activities.
#'
#' @param S0 Initial stock price (positive)
#' @param K Strike price (positive)
#' @param r Gross risk-free rate per period (e.g., 1.05 for 5\% rate)
#' @param u Base up factor in CRR model (e.g., 1.2)
#' @param d Base down factor in CRR model (e.g., 0.8)
#' @param lambda Price impact coefficient (non-negative)
#' @param v_u Hedging volume on up move (non-negative)
#' @param v_d Hedging volume on down move (non-negative)
#' @param n Number of time steps (positive integer)
#'
#' @return European put option price
#'
#' @details
#' The function computes the European put option price using the CRR binomial
#' model with price impact. The pricing formula is:
#' \deqn{V_0 = \frac{1}{r^n} \sum_{k=0}^{n} \binom{n}{k} p_{eff}^k (1-p_{eff})^{n-k} \max(0, K - S_n(k))}
#'
#' where \eqn{S_n(k) = S_0 \tilde{u}^k \tilde{d}^{n-k}} is the stock price after k up moves.
#'
#' Price impact modifies the up and down factors:
#' - Adjusted up factor: \eqn{\tilde{u} = u \exp(\lambda v^u)}
#' - Adjusted down factor: \eqn{\tilde{d} = d \exp(-\lambda v^d)}
#' - Adjusted risk-neutral probability: \eqn{p_{adj} = \frac{r - \tilde{d}}{\tilde{u} - \tilde{d}}}
#'
#' @references
#' Cox, J. C., Ross, S. A., & Rubinstein, M. (1979). Option pricing:
#' A simplified approach. Journal of Financial Economics, 7(3), 229-263.
#' \doi{10.1016/0304-405X(79)90015-1}
#'
#' @examples
#' \dontrun{
#' # Basic example with 10 time steps
#' price_european_put_cpp(
#'   S0 = 100, K = 100, r = 1.05, u = 1.2, d = 0.8,
#'   lambda = 0.1, v_u = 1.0, v_d = 1.0, n = 10
#' )
#' }
#'
#' @export
price_european_put_cpp <- function(S0, K, r, u, d, lambda, v_u, v_d, n) {
    .Call(`_AsianOption_price_european_put_cpp`, S0, K, r, u, d, lambda, v_u, v_d, n)
}

generate_all_paths <- function(n) {
    .Call(`_AsianOption_generate_all_paths`, n)
}

#' Price Geometric Asian Option with Price Impact
#'
#' Computes the exact price of a geometric Asian option (call or put) using the
#' binomial tree model with price impact from hedging activities.
#'
#' @param S0 Initial stock price (positive)
#' @param K Strike price (positive)
#' @param r Gross risk-free rate per period (e.g., 1.05 for 5\% rate)
#' @param u Base up factor in CRR model (e.g., 1.2)
#' @param d Base down factor in CRR model (e.g., 0.8)
#' @param lambda Price impact coefficient (non-negative)
#' @param v_u Hedging volume on up move (non-negative)
#' @param v_d Hedging volume on down move (non-negative)
#' @param n Number of time steps (positive integer)
#' @param option_type Type of option: "call" or "put" (default: "call")
#'
#' @return Geometric Asian option price
#'
#' @details
#' The function uses exact enumeration, computing all 2^n possible price paths:
#' \itemize{
#'   \item Geometric average: \eqn{G = (S_0 \cdot S_1 \cdot \ldots \cdot S_n)^{1/(n+1)}}
#'   \item Call payoff: \eqn{\max(0, G - K)}
#'   \item Put payoff: \eqn{\max(0, K - G)}
#'   \item Option value: \eqn{(1/r^n) \cdot \sum_{paths} p^k (1-p)^{(n-k)} \cdot payoff}
#' }
#'
#' This is an exact calculation (no sampling or approximation).
#'
#' Price impact modifies the up and down factors:
#' \itemize{
#'   \item Adjusted up factor: \eqn{u_{tilde} = u \cdot \exp(\lambda \cdot v_u)}
#'   \item Adjusted down factor: \eqn{d_{tilde} = d \cdot \exp(-\lambda \cdot v_d)}
#' }
#'
#' @references
#' Cox, J. C., Ross, S. A., & Rubinstein, M. (1979). Option pricing:
#' A simplified approach. Journal of Financial Economics, 7(3), 229-263.
#'
#' @examples
#' \dontrun{
#' # Call option example with 3 time steps
#' price_geometric_asian_cpp(
#'   S0 = 100, K = 100, r = 1.05, u = 1.2, d = 0.8,
#'   lambda = 0.1, v_u = 1.0, v_d = 1.0, n = 3, option_type = "call"
#' )
#'
#' # Put option example
#' price_geometric_asian_cpp(
#'   S0 = 100, K = 100, r = 1.05, u = 1.2, d = 0.8,
#'   lambda = 0.1, v_u = 1.0, v_d = 1.0, n = 3, option_type = "put"
#' )
#' }
#'
#' @export
price_geometric_asian_cpp <- function(S0, K, r, u, d, lambda, v_u, v_d, n, option_type = "call") {
    .Call(`_AsianOption_price_geometric_asian_cpp`, S0, K, r, u, d, lambda, v_u, v_d, n, option_type)
}

#' Kemna-Vorst Monte Carlo Simulation for Arithmetic Average Asian Option
#'
#' Implements the Kemna-Vorst (1990) Monte Carlo method with variance reduction
#' using the geometric average as a control variate. This is the standard
#' benchmark implementation WITHOUT price impact.
#'
#' @param S0 Initial stock price at time T0
#' @param K Strike price
#' @param r Continuously compounded risk-free rate
#' @param sigma Volatility (annualized)
#' @param T0 Start of averaging period
#' @param T Maturity time
#' @param n Number of averaging points (observations)
#' @param M Number of Monte Carlo simulations
#' @param option_type String: "call" or "put"
#' @param use_control_variate Boolean: use variance reduction (default TRUE)
#' @param seed Integer: random seed for reproducibility (default 0 = no seed)
#'
#' @return List containing:
#' \describe{
#'   \item{price}{Estimated option price}
#'   \item{std_error}{Standard error of the estimate}
#'   \item{lower_ci}{Lower 95\% confidence interval}
#'   \item{upper_ci}{Upper 95\% confidence interval}
#'   \item{geometric_price}{Analytical geometric average price (control variate)}
#'   \item{correlation}{Correlation between arithmetic and geometric payoffs}
#'   \item{variance_reduction_factor}{Ratio of variances (with/without control variate)}
#' }
#'
#' @details
#' The algorithm follows Kemna & Vorst (1990):
#'
#' 1. Generate price paths under risk-neutral dynamics:
#'    \deqn{\log(S_{i+1}) = \log(S_i) + (r - \sigma^2/2)\Delta t + \sigma\sqrt{\Delta t} Z_i}
#'    where \eqn{Z_i \sim N(0,1)}
#'
#' 2. Calculate arithmetic and geometric averages for each path:
#'    \deqn{A = \frac{1}{n+1}\sum_{i=0}^{n} S_i}
#'    \deqn{G = \left(\prod_{i=0}^{n} S_i\right)^{1/(n+1)}}
#'
#' 3. Calculate discounted payoffs:
#'    \deqn{Y = e^{-r\tau} \max(A - K, 0)}
#'    \deqn{W = e^{-r\tau} \max(G - K, 0)}
#'
#' 4. Use control variate method to reduce variance:
#'    \deqn{\hat{C}_{enhanced} = E[W] + \frac{1}{M}\sum_{j=1}^{M}(Y_j - W_j)}
#'
#' where \eqn{E[W]} is the analytical geometric average price.
#'
#' The variance reduction can be dramatic (factor 10-70) because the
#' correlation between arithmetic and geometric averages is typically > 0.95.
#'
#' @references
#' Kemna, A.G.Z. and Vorst, A.C.F. (1990). "A Pricing Method for Options Based
#' on Average Asset Values." \emph{Journal of Banking and Finance}, 14, 113-129.
#'
#' @examples
#' \donttest{
#' # Basic example
#' result <- price_kemna_vorst_arithmetic_cpp(
#'   S0 = 100, K = 100, r = 0.05, sigma = 0.2,
#'   T0 = 0, T = 1, n = 50, M = 10000,
#'   option_type = "call"
#' )
#' print(result$price)
#' print(result$std_error)
#' }
#'
#' @export
price_kemna_vorst_arithmetic_cpp <- function(S0, K, r, sigma, T0, T, n, M, option_type = "call", use_control_variate = TRUE, seed = 0L) {
    .Call(`_AsianOption_price_kemna_vorst_arithmetic_cpp`, S0, K, r, sigma, T0, T, n, M, option_type, use_control_variate, seed)
}

#' Kemna-Vorst Monte Carlo with Binomial Parameters
#'
#' Alternative interface using discrete binomial parameters instead of
#' continuous parameters.
#'
#' @param S0 Initial stock price
#' @param K Strike price
#' @param r Gross risk-free rate per period
#' @param u Up factor
#' @param d Down factor
#' @param n Number of time steps
#' @param M Number of Monte Carlo simulations
#' @param option_type String: "call" or "put"
#' @param use_control_variate Boolean: use variance reduction
#' @param seed Integer: random seed
#'
#' @return List with pricing results (same as price_kemna_vorst_arithmetic_cpp)
#'
#' @export
price_kemna_vorst_arithmetic_binomial_cpp <- function(S0, K, r, u, d, n, M, option_type = "call", use_control_variate = TRUE, seed = 0L) {
    .Call(`_AsianOption_price_kemna_vorst_arithmetic_binomial_cpp`, S0, K, r, u, d, n, M, option_type, use_control_variate, seed)
}

