// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// price_arithmetic_asian_diffusion_mc_cpp
List price_arithmetic_asian_diffusion_mc_cpp(double S0, double K, double r, double sigma, double T_mat, double lambda_T, double I0, double kappa, NumericVector eta_values, double rho, int n_steps, int n_sims, std::string option_type, bool use_control_variate, int seed);
RcppExport SEXP _AsianOption_price_arithmetic_asian_diffusion_mc_cpp(SEXP S0SEXP, SEXP KSEXP, SEXP rSEXP, SEXP sigmaSEXP, SEXP T_matSEXP, SEXP lambda_TSEXP, SEXP I0SEXP, SEXP kappaSEXP, SEXP eta_valuesSEXP, SEXP rhoSEXP, SEXP n_stepsSEXP, SEXP n_simsSEXP, SEXP option_typeSEXP, SEXP use_control_variateSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type S0(S0SEXP);
    Rcpp::traits::input_parameter< double >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type T_mat(T_matSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_T(lambda_TSEXP);
    Rcpp::traits::input_parameter< double >::type I0(I0SEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type eta_values(eta_valuesSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< int >::type n_steps(n_stepsSEXP);
    Rcpp::traits::input_parameter< int >::type n_sims(n_simsSEXP);
    Rcpp::traits::input_parameter< std::string >::type option_type(option_typeSEXP);
    Rcpp::traits::input_parameter< bool >::type use_control_variate(use_control_variateSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(price_arithmetic_asian_diffusion_mc_cpp(S0, K, r, sigma, T_mat, lambda_T, I0, kappa, eta_values, rho, n_steps, n_sims, option_type, use_control_variate, seed));
    return rcpp_result_gen;
END_RCPP
}
// hjb_arithmetic_value_cpp
Rcpp::List hjb_arithmetic_value_cpp(double S0, double K, double T, int N, double sigma, double r_cont, double kappa, double lambda_bar_T, double lambda_bar_P, double k_A, double k_B, double psi_cost, Rcpp::NumericVector eta_vec, double p, double I0, Rcpp::NumericVector control_set, int n_logS, int n_I, int n_Y, double payoff_sign, bool store_policy);
RcppExport SEXP _AsianOption_hjb_arithmetic_value_cpp(SEXP S0SEXP, SEXP KSEXP, SEXP TSEXP, SEXP NSEXP, SEXP sigmaSEXP, SEXP r_contSEXP, SEXP kappaSEXP, SEXP lambda_bar_TSEXP, SEXP lambda_bar_PSEXP, SEXP k_ASEXP, SEXP k_BSEXP, SEXP psi_costSEXP, SEXP eta_vecSEXP, SEXP pSEXP, SEXP I0SEXP, SEXP control_setSEXP, SEXP n_logSSEXP, SEXP n_ISEXP, SEXP n_YSEXP, SEXP payoff_signSEXP, SEXP store_policySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type S0(S0SEXP);
    Rcpp::traits::input_parameter< double >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type T(TSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type r_cont(r_contSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_bar_T(lambda_bar_TSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_bar_P(lambda_bar_PSEXP);
    Rcpp::traits::input_parameter< double >::type k_A(k_ASEXP);
    Rcpp::traits::input_parameter< double >::type k_B(k_BSEXP);
    Rcpp::traits::input_parameter< double >::type psi_cost(psi_costSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type eta_vec(eta_vecSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type I0(I0SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type control_set(control_setSEXP);
    Rcpp::traits::input_parameter< int >::type n_logS(n_logSSEXP);
    Rcpp::traits::input_parameter< int >::type n_I(n_ISEXP);
    Rcpp::traits::input_parameter< int >::type n_Y(n_YSEXP);
    Rcpp::traits::input_parameter< double >::type payoff_sign(payoff_signSEXP);
    Rcpp::traits::input_parameter< bool >::type store_policy(store_policySEXP);
    rcpp_result_gen = Rcpp::wrap(hjb_arithmetic_value_cpp(S0, K, T, N, sigma, r_cont, kappa, lambda_bar_T, lambda_bar_P, k_A, k_B, psi_cost, eta_vec, p, I0, control_set, n_logS, n_I, n_Y, payoff_sign, store_policy));
    return rcpp_result_gen;
END_RCPP
}
// hjb_geometric_value_cpp
Rcpp::List hjb_geometric_value_cpp(double S0, double K, double T, int N, double sigma, double r_cont, double kappa, double lambda_bar_T, double lambda_bar_P, double k_A, double k_B, double psi_cost, Rcpp::NumericVector eta_vec, double p, double I0, Rcpp::NumericVector control_set, int n_logS, int n_I, int n_Y, double payoff_sign, bool store_policy);
RcppExport SEXP _AsianOption_hjb_geometric_value_cpp(SEXP S0SEXP, SEXP KSEXP, SEXP TSEXP, SEXP NSEXP, SEXP sigmaSEXP, SEXP r_contSEXP, SEXP kappaSEXP, SEXP lambda_bar_TSEXP, SEXP lambda_bar_PSEXP, SEXP k_ASEXP, SEXP k_BSEXP, SEXP psi_costSEXP, SEXP eta_vecSEXP, SEXP pSEXP, SEXP I0SEXP, SEXP control_setSEXP, SEXP n_logSSEXP, SEXP n_ISEXP, SEXP n_YSEXP, SEXP payoff_signSEXP, SEXP store_policySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type S0(S0SEXP);
    Rcpp::traits::input_parameter< double >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type T(TSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type r_cont(r_contSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_bar_T(lambda_bar_TSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_bar_P(lambda_bar_PSEXP);
    Rcpp::traits::input_parameter< double >::type k_A(k_ASEXP);
    Rcpp::traits::input_parameter< double >::type k_B(k_BSEXP);
    Rcpp::traits::input_parameter< double >::type psi_cost(psi_costSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type eta_vec(eta_vecSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type I0(I0SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type control_set(control_setSEXP);
    Rcpp::traits::input_parameter< int >::type n_logS(n_logSSEXP);
    Rcpp::traits::input_parameter< int >::type n_I(n_ISEXP);
    Rcpp::traits::input_parameter< int >::type n_Y(n_YSEXP);
    Rcpp::traits::input_parameter< double >::type payoff_sign(payoff_signSEXP);
    Rcpp::traits::input_parameter< bool >::type store_policy(store_policySEXP);
    rcpp_result_gen = Rcpp::wrap(hjb_geometric_value_cpp(S0, K, T, N, sigma, r_cont, kappa, lambda_bar_T, lambda_bar_P, k_A, k_B, psi_cost, eta_vec, p, I0, control_set, n_logS, n_I, n_Y, payoff_sign, store_policy));
    return rcpp_result_gen;
END_RCPP
}
// hjb_arithmetic_quotes_cpp
Rcpp::List hjb_arithmetic_quotes_cpp(double S0, double K, double T, int N, double sigma, double r_cont, double kappa, double lambda_bar_T, double lambda_bar_P, double k_A, double k_B, double psi_cost, Rcpp::NumericVector eta_vec, double p, double I0, Rcpp::NumericVector control_set, int n_logS, int n_I, int n_Y);
RcppExport SEXP _AsianOption_hjb_arithmetic_quotes_cpp(SEXP S0SEXP, SEXP KSEXP, SEXP TSEXP, SEXP NSEXP, SEXP sigmaSEXP, SEXP r_contSEXP, SEXP kappaSEXP, SEXP lambda_bar_TSEXP, SEXP lambda_bar_PSEXP, SEXP k_ASEXP, SEXP k_BSEXP, SEXP psi_costSEXP, SEXP eta_vecSEXP, SEXP pSEXP, SEXP I0SEXP, SEXP control_setSEXP, SEXP n_logSSEXP, SEXP n_ISEXP, SEXP n_YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type S0(S0SEXP);
    Rcpp::traits::input_parameter< double >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type T(TSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type r_cont(r_contSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_bar_T(lambda_bar_TSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_bar_P(lambda_bar_PSEXP);
    Rcpp::traits::input_parameter< double >::type k_A(k_ASEXP);
    Rcpp::traits::input_parameter< double >::type k_B(k_BSEXP);
    Rcpp::traits::input_parameter< double >::type psi_cost(psi_costSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type eta_vec(eta_vecSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type I0(I0SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type control_set(control_setSEXP);
    Rcpp::traits::input_parameter< int >::type n_logS(n_logSSEXP);
    Rcpp::traits::input_parameter< int >::type n_I(n_ISEXP);
    Rcpp::traits::input_parameter< int >::type n_Y(n_YSEXP);
    rcpp_result_gen = Rcpp::wrap(hjb_arithmetic_quotes_cpp(S0, K, T, N, sigma, r_cont, kappa, lambda_bar_T, lambda_bar_P, k_A, k_B, psi_cost, eta_vec, p, I0, control_set, n_logS, n_I, n_Y));
    return rcpp_result_gen;
END_RCPP
}
// hjb_arithmetic_quotes_with_policy_cpp
Rcpp::List hjb_arithmetic_quotes_with_policy_cpp(double S0, double K, double T, int N, double sigma, double r_cont, double kappa, double lambda_bar_T, double lambda_bar_P, double k_A, double k_B, double psi_cost, Rcpp::NumericVector eta_vec, double p, double I0, Rcpp::NumericVector control_set, int n_logS, int n_I, int n_Y);
RcppExport SEXP _AsianOption_hjb_arithmetic_quotes_with_policy_cpp(SEXP S0SEXP, SEXP KSEXP, SEXP TSEXP, SEXP NSEXP, SEXP sigmaSEXP, SEXP r_contSEXP, SEXP kappaSEXP, SEXP lambda_bar_TSEXP, SEXP lambda_bar_PSEXP, SEXP k_ASEXP, SEXP k_BSEXP, SEXP psi_costSEXP, SEXP eta_vecSEXP, SEXP pSEXP, SEXP I0SEXP, SEXP control_setSEXP, SEXP n_logSSEXP, SEXP n_ISEXP, SEXP n_YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type S0(S0SEXP);
    Rcpp::traits::input_parameter< double >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type T(TSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type r_cont(r_contSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_bar_T(lambda_bar_TSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_bar_P(lambda_bar_PSEXP);
    Rcpp::traits::input_parameter< double >::type k_A(k_ASEXP);
    Rcpp::traits::input_parameter< double >::type k_B(k_BSEXP);
    Rcpp::traits::input_parameter< double >::type psi_cost(psi_costSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type eta_vec(eta_vecSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type I0(I0SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type control_set(control_setSEXP);
    Rcpp::traits::input_parameter< int >::type n_logS(n_logSSEXP);
    Rcpp::traits::input_parameter< int >::type n_I(n_ISEXP);
    Rcpp::traits::input_parameter< int >::type n_Y(n_YSEXP);
    rcpp_result_gen = Rcpp::wrap(hjb_arithmetic_quotes_with_policy_cpp(S0, K, T, N, sigma, r_cont, kappa, lambda_bar_T, lambda_bar_P, k_A, k_B, psi_cost, eta_vec, p, I0, control_set, n_logS, n_I, n_Y));
    return rcpp_result_gen;
END_RCPP
}
// hjb_geometric_quotes_with_policy_cpp
Rcpp::List hjb_geometric_quotes_with_policy_cpp(double S0, double K, double T, int N, double sigma, double r_cont, double kappa, double lambda_bar_T, double lambda_bar_P, double k_A, double k_B, double psi_cost, Rcpp::NumericVector eta_vec, double p, double I0, Rcpp::NumericVector control_set, int n_logS, int n_I, int n_Y);
RcppExport SEXP _AsianOption_hjb_geometric_quotes_with_policy_cpp(SEXP S0SEXP, SEXP KSEXP, SEXP TSEXP, SEXP NSEXP, SEXP sigmaSEXP, SEXP r_contSEXP, SEXP kappaSEXP, SEXP lambda_bar_TSEXP, SEXP lambda_bar_PSEXP, SEXP k_ASEXP, SEXP k_BSEXP, SEXP psi_costSEXP, SEXP eta_vecSEXP, SEXP pSEXP, SEXP I0SEXP, SEXP control_setSEXP, SEXP n_logSSEXP, SEXP n_ISEXP, SEXP n_YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type S0(S0SEXP);
    Rcpp::traits::input_parameter< double >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type T(TSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type r_cont(r_contSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_bar_T(lambda_bar_TSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_bar_P(lambda_bar_PSEXP);
    Rcpp::traits::input_parameter< double >::type k_A(k_ASEXP);
    Rcpp::traits::input_parameter< double >::type k_B(k_BSEXP);
    Rcpp::traits::input_parameter< double >::type psi_cost(psi_costSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type eta_vec(eta_vecSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type I0(I0SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type control_set(control_setSEXP);
    Rcpp::traits::input_parameter< int >::type n_logS(n_logSSEXP);
    Rcpp::traits::input_parameter< int >::type n_I(n_ISEXP);
    Rcpp::traits::input_parameter< int >::type n_Y(n_YSEXP);
    rcpp_result_gen = Rcpp::wrap(hjb_geometric_quotes_with_policy_cpp(S0, K, T, N, sigma, r_cont, kappa, lambda_bar_T, lambda_bar_P, k_A, k_B, psi_cost, eta_vec, p, I0, control_set, n_logS, n_I, n_Y));
    return rcpp_result_gen;
END_RCPP
}
// hjb_geometric_quotes_cpp
Rcpp::List hjb_geometric_quotes_cpp(double S0, double K, double T, int N, double sigma, double r_cont, double kappa, double lambda_bar_T, double lambda_bar_P, double k_A, double k_B, double psi_cost, Rcpp::NumericVector eta_vec, double p, double I0, Rcpp::NumericVector control_set, int n_logS, int n_I, int n_Y);
RcppExport SEXP _AsianOption_hjb_geometric_quotes_cpp(SEXP S0SEXP, SEXP KSEXP, SEXP TSEXP, SEXP NSEXP, SEXP sigmaSEXP, SEXP r_contSEXP, SEXP kappaSEXP, SEXP lambda_bar_TSEXP, SEXP lambda_bar_PSEXP, SEXP k_ASEXP, SEXP k_BSEXP, SEXP psi_costSEXP, SEXP eta_vecSEXP, SEXP pSEXP, SEXP I0SEXP, SEXP control_setSEXP, SEXP n_logSSEXP, SEXP n_ISEXP, SEXP n_YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type S0(S0SEXP);
    Rcpp::traits::input_parameter< double >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type T(TSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type r_cont(r_contSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_bar_T(lambda_bar_TSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_bar_P(lambda_bar_PSEXP);
    Rcpp::traits::input_parameter< double >::type k_A(k_ASEXP);
    Rcpp::traits::input_parameter< double >::type k_B(k_BSEXP);
    Rcpp::traits::input_parameter< double >::type psi_cost(psi_costSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type eta_vec(eta_vecSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type I0(I0SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type control_set(control_setSEXP);
    Rcpp::traits::input_parameter< int >::type n_logS(n_logSSEXP);
    Rcpp::traits::input_parameter< int >::type n_I(n_ISEXP);
    Rcpp::traits::input_parameter< int >::type n_Y(n_YSEXP);
    rcpp_result_gen = Rcpp::wrap(hjb_geometric_quotes_cpp(S0, K, T, N, sigma, r_cont, kappa, lambda_bar_T, lambda_bar_P, k_A, k_B, psi_cost, eta_vec, p, I0, control_set, n_logS, n_I, n_Y));
    return rcpp_result_gen;
END_RCPP
}
// price_kemna_vorst_arithmetic_cpp
List price_kemna_vorst_arithmetic_cpp(double S0, double K, double r, double sigma, double T0, double T_mat, int n, int M, std::string option_type, bool use_control_variate, int seed);
RcppExport SEXP _AsianOption_price_kemna_vorst_arithmetic_cpp(SEXP S0SEXP, SEXP KSEXP, SEXP rSEXP, SEXP sigmaSEXP, SEXP T0SEXP, SEXP T_matSEXP, SEXP nSEXP, SEXP MSEXP, SEXP option_typeSEXP, SEXP use_control_variateSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type S0(S0SEXP);
    Rcpp::traits::input_parameter< double >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type T0(T0SEXP);
    Rcpp::traits::input_parameter< double >::type T_mat(T_matSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< std::string >::type option_type(option_typeSEXP);
    Rcpp::traits::input_parameter< bool >::type use_control_variate(use_control_variateSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(price_kemna_vorst_arithmetic_cpp(S0, K, r, sigma, T0, T_mat, n, M, option_type, use_control_variate, seed));
    return rcpp_result_gen;
END_RCPP
}
// price_kemna_vorst_arithmetic_binomial_cpp
List price_kemna_vorst_arithmetic_binomial_cpp(double S0, double K, double r, double u, double d, int n, int M, std::string option_type, bool use_control_variate, int seed);
RcppExport SEXP _AsianOption_price_kemna_vorst_arithmetic_binomial_cpp(SEXP S0SEXP, SEXP KSEXP, SEXP rSEXP, SEXP uSEXP, SEXP dSEXP, SEXP nSEXP, SEXP MSEXP, SEXP option_typeSEXP, SEXP use_control_variateSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type S0(S0SEXP);
    Rcpp::traits::input_parameter< double >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type u(uSEXP);
    Rcpp::traits::input_parameter< double >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< std::string >::type option_type(option_typeSEXP);
    Rcpp::traits::input_parameter< bool >::type use_control_variate(use_control_variateSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(price_kemna_vorst_arithmetic_binomial_cpp(S0, K, r, u, d, n, M, option_type, use_control_variate, seed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_AsianOption_price_arithmetic_asian_diffusion_mc_cpp", (DL_FUNC) &_AsianOption_price_arithmetic_asian_diffusion_mc_cpp, 15},
    {"_AsianOption_hjb_arithmetic_value_cpp", (DL_FUNC) &_AsianOption_hjb_arithmetic_value_cpp, 21},
    {"_AsianOption_hjb_geometric_value_cpp", (DL_FUNC) &_AsianOption_hjb_geometric_value_cpp, 21},
    {"_AsianOption_hjb_arithmetic_quotes_cpp", (DL_FUNC) &_AsianOption_hjb_arithmetic_quotes_cpp, 19},
    {"_AsianOption_hjb_arithmetic_quotes_with_policy_cpp", (DL_FUNC) &_AsianOption_hjb_arithmetic_quotes_with_policy_cpp, 19},
    {"_AsianOption_hjb_geometric_quotes_with_policy_cpp", (DL_FUNC) &_AsianOption_hjb_geometric_quotes_with_policy_cpp, 19},
    {"_AsianOption_hjb_geometric_quotes_cpp", (DL_FUNC) &_AsianOption_hjb_geometric_quotes_cpp, 19},
    {"_AsianOption_price_kemna_vorst_arithmetic_cpp", (DL_FUNC) &_AsianOption_price_kemna_vorst_arithmetic_cpp, 11},
    {"_AsianOption_price_kemna_vorst_arithmetic_binomial_cpp", (DL_FUNC) &_AsianOption_price_kemna_vorst_arithmetic_binomial_cpp, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_AsianOption(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
